[package]
name = "gpx-to-kml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpx = "0.8.6"
kml = "0.7.1"
